const { chromium } = require(process.env.ASENT_PLAYWRIGHT || 'playwright');
const fs = require('fs');
(async()=>{
 const bundled=process.env.ASENT_CHROMIUM_MODULE?(await import(process.env.ASENT_CHROMIUM_MODULE)).default:null;
 const browser=await chromium.launch({headless:true,args:bundled?bundled.args:['--no-sandbox'],...(bundled?{executablePath:process.env.ASENT_CHROMIUM_EXECUTABLE||await bundled.executablePath()}: {})});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Project intake',exact:true}).click();
 await page.locator('input[type=file]').setInputFiles('demo_project/InvoiceHub/SRS.md');
 await page.getByRole('textbox').filter({hasText:'FR-03'}).count();
 await page.getByRole('button',{name:'Threat Repository',exact:true}).click();
 await page.getByRole('tab',{name:/Behavior rules/}).waitFor();
 await page.getByLabel('Search threat records').fill('NETWORK_CONNECT');
 await page.getByLabel('Inspect BEH-NETWORK_CONNECT').click();
 await page.getByLabel('Close record').click();
 await page.getByLabel('Search threat records').fill('');
 await page.screenshot({path:'reports/dashboard-threat-repository.png',fullPage:true});
 await page.getByRole('button',{name:'Live development',exact:true}).click();
 await page.getByRole('button',{name:'Run safe scenario',exact:true}).click();
 await page.getByText('Ready for a trusted handoff.',{exact:true}).waitFor({timeout:120000});
 await page.screenshot({path:'reports/dashboard-safe-accept.png',fullPage:true});
 for(const name of ['CAVR','SATRA-RV','SABLE','Integrated evidence','Final trust gate']){
  await page.getByRole('button',{name,exact:true}).click();
  await page.screenshot({path:'reports/dashboard-'+name.replace(/ /g,'-')+'.png',fullPage:true});
 }
 const sse=await page.evaluate(async()=>{const runs=await (await fetch('/api/runs')).json();return await new Promise((resolve,reject)=>{const s=new EventSource('/api/runs/'+runs[0].run_id+'/stream');s.onmessage=e=>{s.close();resolve(JSON.parse(e.data).kind)};s.onerror=()=>{s.close();reject(Error('SSE unavailable'))}})});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 await page.getByRole('button',{name:'InvoiceHub app',exact:true}).click();
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByText('Upload a PDF invoice',{exact:true}).waitFor();
 await page.locator('input[type=file]').setInputFiles('demo_project/InvoiceHub/fixtures/invoice.pdf');
 await page.getByRole('button',{name:'Upload invoice',exact:true}).click();
 await page.getByRole('cell',{name:'invoice.pdf',exact:true}).first().waitFor();
 await page.screenshot({path:'reports/dashboard-invoicehub.png',fullPage:true});
 await page.getByRole('button',{name:'Threat Repository',exact:true}).click();
 await page.getByRole('tab',{name:/Trigger patterns/}).click();
 await page.getByRole('switch',{name:'Enable TRIG-ENV',exact:true}).click();
 await page.getByRole('status').waitFor();
 await page.getByRole('button',{name:'Final trust gate',exact:true}).click();
 await page.getByRole('heading',{name:'REVIEW',exact:true}).waitFor({timeout:10000});
 await page.screenshot({path:'reports/dashboard-knowledge-invalidated.png',fullPage:true});
 await page.getByRole('button',{name:'Threat Repository',exact:true}).click();
 await page.getByRole('tab',{name:/Trigger patterns/}).click();
 await page.getByRole('switch',{name:'Enable TRIG-ENV',exact:true}).click();
 await page.getByRole('status').waitFor();
 await page.setViewportSize({width:900,height:900});
 await page.screenshot({path:'reports/dashboard-responsive.png',fullPage:true});
 fs.writeFileSync('reports/browser-validation.json',JSON.stringify({checked_at:new Date().toISOString(),errors,sse_first_event:sse,desktop_horizontal_overflow:overflow,checks:['threat search and provenance','safe run acceptance','all three module views','evidence and final gate','real PDF login/upload','knowledge toggle revokes ACCEPT','restore knowledge','900px responsive view']},null,2));
 await browser.close();if(errors.length||overflow)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
