"""Curated reusable knowledge with provenance. No precomputed security verdicts."""
import json
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from backend.config import ROOT
from backend.satra.dictionary import RULES
D=ROOT/'backend/threat_repo/seed';D.mkdir(exist_ok=True)
STAMP='2026-09-26T00:00:00+00:00'
def row(id,cat,name,description='',severity='INFO',source='SRC-ASENT',**data):return {'id':id,'category':cat,'name':name,'description':description,'severity':severity,'source_id':source,'enabled':True,'version':1,'updated_at':STAMP,'data':data}
def save(name,rows):(D/(name+'.json')).write_text(json.dumps({'records':rows},indent=2))
sources=[
 row('SRC-ASENT','sources','ASENT curated program-analysis knowledge','Bounded patterns and policies from the supplied project designs. Research hypotheses, not validated prevalence claims.',source='SRC-ASENT',source_type='ASENT curated rule',reference='docs/implementation-notes.md',trust_class='curated',license_note='Project-authored knowledge; inspect and evaluate',retrieved_at=STAMP),
 row('SRC-LAB','sources','InvoiceHub controlled reproduction','Only synthetic conditions and fake canary bytes; not evidence of an observed malicious package selection.',source='SRC-LAB',source_type='controlled reproduction',reference='scenarios/cavr_controlled/invoice_pdf_lab.py',trust_class='controlled',license_note='Project-authored inert fixture',retrieved_at=STAMP),
 row('SRC-OSV','sources','OSV public vulnerability data','Imported responses retain query, source URL, retrieval date and digest.',source='SRC-OSV',source_type='OSV',reference='https://google.github.io/osv.dev/api/',trust_class='public advisory',license_note='Advisories retain upstream source/license; attribution preserved',retrieved_at=STAMP),
 row('SRC-AWS','sources','AWS S3 least privilege guidance','Principal, action and resource relationships motivate the bounded model.',source='SRC-AWS',source_type='official advisory',reference='https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html',trust_class='official documentation',license_note='Paraphrased rule; no documentation text redistributed',retrieved_at=STAMP),
 row('SRC-TERRAFORM','sources','Terraform refactoring documentation','Explicit moved blocks are one correspondence signal.',source='SRC-TERRAFORM',source_type='public tool',reference='https://developer.hashicorp.com/terraform/language/modules/develop/refactoring',trust_class='official documentation',license_note='Paraphrased semantics',retrieved_at=STAMP),
 row('SRC-OWASP','sources','OWASP secure coding with AI guidance','Independent security tests and validation of generated work.',source='SRC-OWASP',source_type='public tool',reference='https://cheatsheetseries.owasp.org/cheatsheets/Secure_Coding_with_AI_Cheat_Sheet.html',trust_class='public guidance',license_note='Original ASENT test templates; OWASP source cited',retrieved_at=STAMP),
]
save('sources',sources)
behavior=[('SECRET_READ','HIGH',[]),('SENSITIVE_FILE_READ','HIGH',[]),('FILE_READ','LOW',[]),('FILE_WRITE','MEDIUM',[]),('NETWORK_CONNECT','MEDIUM',['socket.create_connection','socket.connect','requests.post','requests.get','urllib.request.urlopen']),('PROCESS_EXEC','HIGH',['subprocess.run','subprocess.Popen','os.system']),('NATIVE_EXEC','HIGH',[]),('PERSISTENCE_WRITE','HIGH',[]),('DYNAMIC_DOWNLOAD','HIGH',[]),('DYNAMIC_EXECUTION','HIGH',['eval','exec'])]
save('behaviors',[row('BEH-'+name,'behaviors',name,'Security-sensitive capability; compare scope and project justification before deciding.',sev,event=name,python_sinks=calls,runtime_event={'SECRET_READ':'SECRET_ACCESS','PROCESS_EXEC':'PROCESS_CREATE','DYNAMIC_EXECUTION':'NATIVE_EXEC'}.get(name,name)) for name,sev,calls in behavior])
triggers=[('ENV','environment-variable check',10,['os.getenv','os.environ.get']),('FILE','sensitive-file existence',10,['.exists','.is_file','os.path.exists']),('HOST','hostname condition',7,['socket.gethostname','platform.node']),('USER','username condition',7,['getpass.getuser','os.getlogin']),('PLATFORM','OS/platform condition',6,['platform.system','platform.platform']),('TIME','date/time condition',6,['time.','datetime.']),('DELAY','sleep/delay',6,['time.sleep']),('CLOUD','CI/cloud flag',9,['os.getenv','os.environ.get']),('METADATA','cloud metadata condition',10,['requests.get','urllib.request.urlopen']),('SANDBOX','sandbox/container detection',8,['os.path.exists','.exists']),('RESPONSE','external-response dependent behavior',8,['requests.get','requests.post'])]
save('triggers',[row('TRIG-'+id,'triggers',name,'Prioritize when predicate controls a security-sensitive sink. Unsupported activation remains unresolved.','HIGH',category=name,risk_weight=weight,match_calls=calls,activation_supported=id=='ENV') for id,name,weight,calls in triggers])
flows=[('SECRET-NET','SECRET_READ','NETWORK_CONNECT'),('SSH-NET','SSH_KEY_READ','NETWORK_CONNECT'),('CRED-PROC','CREDENTIAL_READ','PROCESS_EXEC'),('DOWNLOAD-PROC','DYNAMIC_DOWNLOAD','PROCESS_EXEC'),('FILE-NET','SENSITIVE_FILE_READ','NETWORK_CONNECT')]
save('source_sink',[row('BEH-'+id+'-001','source_sink',a+' → '+b,'Correlate source and sink with causal evidence and project permissions; co-occurrence alone is not malware.','HIGH',source_event=a,sink_event=b,preconditions=['source/sink attribution','unjustified capability'],rationale='Prevent unjustified data movement or execution') for id,a,b in flows])
save('capability_rules',[
 row('CAP-PDF-001','capability_rules','Local PDF extraction','Reading supplied PDFs and temporary files is justified. Secrets, persistence and arbitrary subprocess/network access are not.','MEDIUM',task='pdf extraction',required=[{'capability':'FILE_READ','scope':'supplied PDF'},{'capability':'FILE_WRITE','scope':'temporary workspace'}],denied=['SECRET_ACCESS','NETWORK_CONNECT','PROCESS_CREATE','PERSISTENCE_WRITE','EXECUTE_BINARY']),
 row('CAP-HTTP-001','capability_rules','Scoped HTTP client','A justified HTTP client may connect to approved endpoints. Network use alone is not a maliciousness decision.','MEDIUM',task='http client',required=[{'capability':'NETWORK_CONNECT','scope':'approved endpoints'}],denied=['SECRET_ACCESS','PERSISTENCE_WRITE','PROCESS_CREATE'])])
satra=[row(r['id'],'satra_rules',r['family'],r['expected_secure_behavior'],'HIGH',source='SRC-OWASP',**{k:v for k,v in r.items() if k!='id'},implementation='executable bounded InvoiceHub template') for r in RULES]
for id,cwe,name,hint in [('SQL','CWE-89','SQL injection','unparameterized query construction'),('CMD','CWE-78','Command injection','user input reaches shell'),('PATH','CWE-22','Path traversal','missing path containment'),('XSS','CWE-79','XSS','unescaped user content to HTML'),('SSRF','CWE-918','SSRF','user URL reaches unrestricted HTTP client'),('CSRF','CWE-352','CSRF','ambient cookie authentication on state-changing routes'),('DESER','CWE-502','Insecure deserialization','untrusted pickle/yaml object construction')]:
 satra.append(row('SATRA-'+id,'satra_rules',name,'Bounded family knowledge; dynamic coverage is not claimed for this family.','HIGH',source='SRC-OWASP',cwe=cwe,family=name,detection_hints=[hint],applicability=['Python web application'],pytest_template=None,counterfactual_template=None,weak_test_indicators=['no negative case','assertion removed','unconditional auth mock'],validation_rules=['parses','secure baseline passes','valid counterfactual killed','stable','local'],implementation='knowledge only; no universal dynamic template'))
save('satra_rules',satra)
save('sable_rules',[
 row('SABLE-S3IAM-001','sable_rules','Role-to-protected-S3 least privilege','The original action/resource obligation must hold on a uniquely supported successor.','HIGH',source='SRC-AWS',principal_action_resource=True,allowed_actions=['s3:GetObject','s3:PutObject'],wrong_binding=True,privilege_widening=True,unsupported_semantics='UNKNOWN'),
 row('SABLE-SUCCESSOR-001','sable_rules','Unique evidence-supported successor','Use multiple structural signals and explicit moves; do not use resource-name similarity as proof.','HIGH',source='SRC-TERRAFORM',minimum_score=6,margin=3,signals=['type','physical bucket','Asset tag','lifecycle role','application references','moved blocks'])])
save('package_threats',[row('PKG-LAB-001','package_threats','Invoice PDF laboratory sample','This is an inert controlled reproduction, not a real malicious package. A name match is supporting context only.','MEDIUM',source='SRC-LAB',ecosystem='LOCAL',package='invoice-pdf-lab',version='1.0.0',classification='controlled suspicious behavior',confidence='controlled',artifact_hash=None,verdict_from_name=False)])
save('vulnerabilities',[row('PYSEC-2026-3005.0','vulnerabilities','pypdf circular reference-stream loop','Crafted PDF cross-reference metadata can prevent the reader from terminating. Fixed in 6.7.2.','LOW',source='SRC-OSV',ecosystem='PyPI',package='pypdf',ranges=[{'type':'ECOSYSTEM','events':[{'introduced':'0'},{'fixed':'6.7.2'}]}],versions=[],advisory_id='PYSEC-2026-3005',aliases=['CVE-2026-27628','GHSA-2rw7-x74f-jg35'],retrieved_at=STAMP,last_updated='2026-07-13T16:33:08.814408153Z',reference='https://osv.dev/vulnerability/PYSEC-2026-3005',retrieval_method='Reviewed public OSV web record; transcribed range facts, not a fabricated API response')])
print('Versioned knowledge seeds written')
